name: get_shadcn
description: "Compatibility between 'shadcn_flutter' and 'get'"
version: 4.6.6
#homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shadcn_flutter: ^0.0.22

dev_dependencies:
  surf_lint_rules: ^3.1.0
#flutter:
